# Generated by Django 5.0.2 on 2024-02-19 19:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='time_create',
        ),
        migrations.RemoveField(
            model_name='article',
            name='time_update',
        ),
        migrations.AddField(
            model_name='article',
            name='number',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
