# Generated by Django 5.0.2 on 2024-02-19 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_article_time_create_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='cat',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='number',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='number',
            new_name='order',
        ),
    ]
